In [1]:
# import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
# load in the data

rawDF = pd.read_csv("Titanic-Dataset.csv.xls")

rawDF.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
rawDF.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [4]:
rawDF["Survived"].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [5]:
def printAmtNA(aDF):
   for aCol in aDF:
    print(f"The amount of missing values in {aCol} is {aDF[aCol].isna().sum()}")

printAmtNA(rawDF)

The amount of missing values in PassengerId is 0
The amount of missing values in Survived is 0
The amount of missing values in Pclass is 0
The amount of missing values in Name is 0
The amount of missing values in Sex is 0
The amount of missing values in Age is 177
The amount of missing values in SibSp is 0
The amount of missing values in Parch is 0
The amount of missing values in Ticket is 0
The amount of missing values in Fare is 0
The amount of missing values in Cabin is 687
The amount of missing values in Embarked is 2

In [6]:
droppedDF = rawDF.drop(columns=['Cabin'])

droppedDF = droppedDF.drop(columns=['Name'])

droppedDF = droppedDF.drop(columns=['Ticket'])

droppedDF

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,male,22.0,1,0,7.2500,S
1,2,1,1,female,38.0,1,0,71.2833,C
2,3,1,3,female,26.0,0,0,7.9250,S
3,4,1,1,female,35.0,1,0,53.1000,S
4,5,0,3,male,35.0,0,0,8.0500,S
...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.0,0,0,13.0000,S
887,888,1,1,female,19.0,0,0,30.0000,S
888,889,0,3,female,NaN,1,2,23.4500,S
889,890,1,1,male,26.0,0,0,30.0000,C
890,891,0,3,male,32.0,0,0,7.7500,Q

In [7]:
from sklearn.impute import SimpleImputer

import numpy as np

imputer = SimpleImputer(strategy="mean")

imputedDF = droppedDF.copy()
imputedDF["Age"] = imputer.fit_transform(imputedDF[["Age"]])

imputedDF.tail()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
886,887,0,2,male,27.000000,0,0,13.00,S
887,888,1,1,female,19.000000,0,0,30.00,S
888,889,0,3,female,29.699118,1,2,23.45,S
889,890,1,1,male,26.000000,0,0,30.00,C
890,891,0,3,male,32.000000,0,0,7.75,Q

In [8]:
rowRemoveDF = imputedDF.dropna(axis=0)

rowRemoveDF

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,male,22.000000,1,0,7.2500,S
1,2,1,1,female,38.000000,1,0,71.2833,C
2,3,1,3,female,26.000000,0,0,7.9250,S
3,4,1,1,female,35.000000,1,0,53.1000,S
4,5,0,3,male,35.000000,0,0,8.0500,S
...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.000000,0,0,13.0000,S
887,888,1,1,female,19.000000,0,0,30.0000,S
888,889,0,3,female,29.699118,1,2,23.4500,S
889,890,1,1,male,26.000000,0,0,30.0000,C
890,891,0,3,male,32.000000,0,0,7.7500,Q

In [9]:
categoricalCols = ["Sex", "Embarked", "Pclass"]

categoricalCols

['Sex', 'Embarked', 'Pclass']

In [10]:
from sklearn.preprocessing import OneHotEncoder

# instantiate and fit the one hot encoder
encoder = OneHotEncoder(sparse_output=False)
encoderArray = encoder.fit_transform(rowRemoveDF[categoricalCols])
colNames = encoder.get_feature_names_out()

# fix the shape
colNames = np.array(colNames).ravel()

# get the dataframe of the 
oneHotDF = pd.DataFrame(encoderArray, columns=colNames)

oneHotDF.head()

,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Pclass_1,Pclass_2,Pclass_3
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
1,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
4,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0

In [11]:

rowRemoveDF = rowRemoveDF.drop(columns = categoricalCols)

rowRemoveDF = pd.concat([rowRemoveDF, oneHotDF], axis=1)

rowRemoveDF.head()

,PassengerId,Survived,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Pclass_1,Pclass_2,Pclass_3
0,1.0,0.0,22.0,1.0,0.0,7.2500,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
1,2.0,1.0,38.0,1.0,0.0,71.2833,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2,3.0,1.0,26.0,0.0,0.0,7.9250,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,4.0,1.0,35.0,1.0,0.0,53.1000,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
4,5.0,0.0,35.0,0.0,0.0,8.0500,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0

In [12]:
processedDF = rowRemoveDF.dropna(axis=0)

processedDF

,PassengerId,Survived,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Pclass_1,Pclass_2,Pclass_3
0,1.0,0.0,22.000000,1.0,0.0,7.2500,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
1,2.0,1.0,38.000000,1.0,0.0,71.2833,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2,3.0,1.0,26.000000,0.0,0.0,7.9250,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,4.0,1.0,35.000000,1.0,0.0,53.1000,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
4,5.0,0.0,35.000000,0.0,0.0,8.0500,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,885.0,0.0,25.000000,0.0,0.0,7.0500,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
885,886.0,0.0,39.000000,0.0,5.0,29.1250,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
886,887.0,0.0,27.000000,0.0,0.0,13.0000,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
887,888.0,1.0,19.000000,0.0,0.0,30.0000,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
888,889.0,0.0,29.699118,1.0,2.0,23.4500,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0

In [13]:
yDF = processedDF["Survived"]
xDF = processedDF.drop(columns=["Survived"], axis=1)

print(xDF.columns)
xDF.head()

Index(['PassengerId', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex_female',
       'Sex_male', 'Embarked_C', 'Embarked_Q', 'Embarked_S', 'Pclass_1',
       'Pclass_2', 'Pclass_3'],
      dtype='object')

,PassengerId,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Pclass_1,Pclass_2,Pclass_3
0,1.0,22.0,1.0,0.0,7.2500,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
1,2.0,38.0,1.0,0.0,71.2833,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2,3.0,26.0,0.0,0.0,7.9250,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,4.0,35.0,1.0,0.0,53.1000,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
4,5.0,35.0,0.0,0.0,8.0500,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0

In [14]:
yDF.head()

0    0.0
1    1.0
2    1.0
3    1.0
4    0.0
Name: Survived, dtype: float64

In [15]:
pd.DataFrame(yDF)

     Survived
0         0.0
1         1.0
2         1.0
3         1.0
4         0.0
..        ...
884       0.0
885       0.0
886       0.0
887       1.0
888       0.0

[887 rows x 1 columns]

In [16]:
from sklearn.model_selection import train_test_split

xTrain, xTest, yTrain, yTest = train_test_split(
    xDF, yDF, 
    test_size=0.05,
    shuffle = True,
    stratify = yDF)

In [17]:
from sklearn.preprocessing import StandardScaler

xScaler = StandardScaler()
xColNames = xTrain.columns.values.tolist()
# train the scaler and apply it to the training set
xTrainScaled = xScaler.fit_transform(xTrain[xColNames])